### ISSUE TITLE
Opt-In Funktionalität für Cookies/Google Analytics

### ISSUE THREAD

**Issue by CptPhynex** [Kicktemp/kickgdpr#2]
Moin,

ich würde gerne die Opt-In Funktionalität des PlugIns nutzen. Sprich Cookies (ausgenommen Standard-Session-Cookies von Joomla wenn möglich/nötig) sollen solang gesperrt sein, bis User "Cookies akzeptieren" drücken oder eben gesperrt bleiben, wenn "Cookies ablehnen" gedrückt wird. Leider werden ich aus dem im Backend verlinkten Code (https://cookieconsent.insites.com/documentation/disabling-cookies/) nicht so ganz schlau. Wo/in welcher Form müsste ich den einbinden, damit das funktioniert?

Das ganze ist nötig, da bei mir (auch wenn datenschutzbedenklich) Slider von Facebook und Twitter und Dienste von Google Analytics eingebunden sind, die beim Aufrufen der Seite direkt einen Cookie setzen. Dies soll auf diese Weise ohne Zustimmung des Nutzers verhindert werden, sodass dieser selbst entscheiden kann.

Vielen Dank schon mal im Voraus.

Gruß, Phynex

**Comment by tecpromotion** [comment]
Wie werden denn die Inhalte in die Seite eingebunden? Mittels einem Plugin/Module?

Gerne mehr Infos an hello@kicktemp.com senden mit URL etc. Dann schauen wir uns das gerne an.

**Comment by nielsnuebel** [comment]
Moin, 

du kannst sonst auch das Javascript welches dafür benötigt wird in das Custom Code Feld packen.

Kannst es ja gerne mal mit einem alert('test'); testen.
![gdpr](https://user-images.githubusercontent.com/3214077/43193751-236e9e04-9001-11e8-83c0-9e0c2590516b.gif)

**Comment by CptPhynex** [comment]
@tecpromotion 
Facebook/Twitter Slider sind über die "Facebook Likebox Slider"-Erweiterung von JS Network Solutions (https://jsns.eu/products/js-facebook-likebox-slider) als Modul eingebunden. 
Google Analytics über eure Erweiterung.

Beim Öffnen der Seite werden dann im Moment noch direkt folgende Cookies gesetzt: https://abload.de/img/downloade6it5.png

@nielsnuebel 
Hättest du zufällig ein entsprechendes JavaScript zur Hand? Hab da schon bisschen was ausprobiert, hat aber immer dazu geführt, dass am Ende gar kein Cookie Hinweis mehr aufgeplopt war.

**Comment by CptPhynex** [comment]
Ich habe den oben genannten Slider nun komplett entfernt, sodass ein Opt-In nicht mehr nötig ist und ich nur noch einen normalen Hinweis-Text setzen muss. Ansonsten wird das zu kompliziert und aus datenschutzrechtlicher Sicht zu bedenklich.

Danke dennoch für die Hilfe.
