### ISSUE TITLE
Button change after updating PHP and plugin

### ISSUE THREAD

**Issue by bayareajenn** [Kicktemp/kickgdpr#8]
Hi there,

I updated PHP and then Kick GDPR on two sites, nearly identical, same server, template, etc. On one of them, the button now is below the text and spans the width of the template. I cannot figure out how to get it back to normal. The other site is totally fine. I can find no difference in settings or CSS. So strange. I even uninstalled it and reinstalled it and had the same problem. Also cleared all cache.

Can you please take a look and tell me where I can fix it?

(removed link)

Thanks in advance,
Jenn

**Comment by tecpromotion** [comment]
Hi @bayareajenn 
Did you currently disable the plugin? Google Analytics is integrated in the source code but not via the kickgdpr plugin.

I'll take a look at it as soon as you reactivate it.

**Comment by tecpromotion** [comment]
Hi Jenn,

I can't see it here: https://www.acpinternational.com/

Google analytics and facebook pixel are not integrated with our plugin.

I can offer you to send us the credentials for a Super Administrator to support@kicktemp.com. I'll take a look at it later.

Greeting Stefan

**Comment by bayareajenn** [comment]
Thanks Stefan. I can't see it either but I thought it was because I
accepted cookies on Friday. I'm in Texas and I just got up. In about an
hour or so I'll set you up with admin and email you.

Thanks for your help. More shortly via email.

Jenn

**Comment by bayareajenn** [comment]
Hi Stefan!

I've just emailed the credentials to support@.

Would you mind please removing the domain from your previous message for me? I put it in the email for you and don't want it getting indexed here in github. I removed it from my initial post already.

Thanks!
Jenn

**Comment by bayareajenn** [comment]
For others who might come across this issue, it was a conflict with the RokBox plugin by RocketTheme. Thanks Stefan for all your help!! 
Jenn
